package help;

public class HelpData {
  public final static String[] getData() {
    return helps;
  }

  private final static String[] helps=new String[] {

    "#<'(Xs): sets the dcg token list to be Xs for processing by assumption grammar -- assumptions.pl",
    "'#*'(X): adds 'intuitionisic' assumption *(X) to be used indefinitely by '#-' operation -- assumptions.pl",
    "'#+'(X): adds 'linear' assumption +(X) to be consumed at most once, by a '#-' operation -- assumptions.pl",
    "'#-'(X): consumes +(X) linear assumption or matches *(X) intuitionistic assumption -- assumptions.pl",
    "'#:'(X): matches X against current dcg token the assumption grammar is working on -- assumptions.pl",
    "'#='(X): unifies X with any matching existing or future +(X) linear assumptions -- assumptions.pl",
    "'#>'(Xs): unifies current assumption grammar token list with Xs -- assumptions.pl",
    "'#?'(X): matches +(X) or *(X) assumptions without any binding -- assumptions.pl",
    "-(A,B): computes the opposite value B of A, B is -A -- xbuiltins.pl",
    "=..(Term,List) : called 'univ' - converts between F(X1..Xs) and [F,X1,..Xn] -- lib.pl",
    "?G: debugging made simple: atoms annotated with '?' will have their evaluation traced -- meta.pl",
    "A @< B : true if A is smaller than B in standard order -- sort.pl",
    "A @=< B : true if A is smaller or equal than B in standard order -- sort.pl",
    "A @> B : true if A is larger than B in standard order -- sort.pl",
    "A @>= B : true if A is larger or equal than B in standard order -- sort.pl",
    "A==B : is true if A and B are structurally the same (correesponding vars being also identical) -- sort.pl",
    "A\\==B : is true if A and B are not structurally the same, negation of '==' -- sort.pl",
    "Agent@SimpleGoal: calls SimpleGoal using Agent's local Db -- lagent.pl",
    "Agent@[Super_1,...,Super_n]. Defines an Agent that inherits scripts form a list of Supers in the same space -- lagent.pl",
    "Sym <= Val: sets a thread-local variable Sym to Val -- xbuiltins.pl",
    "Sym => Val: gets value Val of a thread-local variable Sym -- xbuiltins.pl",
    "Var <== Val: sets a global variable -- xbuiltins.pl",
    "Var ==> Val: gets the value of a global variable -- xbuiltins.pl",
    "X is E: calls arithmetic evaluator on E - result to be unified with X -- shared.pl",
    "X:G~>LazyList: list comprehension syntax for lazy_findall -- engine.pl",
    "[File] or compile(File): compiles in new name space File.pl (or File.wam, if newer) -- lfix.pl",
    "abolish(F/N), abolish(F,N): discards predicate F/N, calling it later triggers an error -- db.pl",
    "abolish_dynamic(F/N): discards predicate F/N, such that calling it later just fails -- db.pl",
    "abs(A,B): computes absolute value B of A -- xbuiltins.pl",
    "abs2path_file(Abs,Path,File): splits an absolute file name into Path and File -- xio.pl",
    "add_task(G): add to default task group a task producing instances of G -- xtask.pl",
    "add_task(X,G): add to default task group a task producing answers X while running G -- xtask.pl",
    "add_task(X,G,TG) : adds a task (X:-G) to a task group TG - it also creates TG, if needed -- xtask.pl",
    "add_to_path(Dir): ads Dir to end of search path for find_file -- xbuiltins.pl",
    "adds a new term to the list -- xbuiltins.pl",
    "alt_findall(X,G,Xs): collects to a list Xs copies of all answers X of G using engines -- engine.pl",
    "alternative inner server API -- xnet.pl",
    "append(Xs,Ys,Zs): true if Zs is the concatenation of lists Xs and Ys -- lists.pl",
    "append(Xss,Xs): Xs is the concatentation of Xss obtained by folding with append/3 -- lists.pl",
    "apply_do_after_load is called before toploop to run dynamic events shcheduled by the compiler -- xtop.pl",
    "arg(N,T,X): selects N-th argument of term T, function symbol if N=0 -- builtins.pl",
    "argn(I,T,X): backtracks applying arg(I,Y,X) over all args of T (arg 0 included) -- lib.pl",
    "arity(T,N): returns arity of term T -- builtins.pl",
    "array_get(A,I,R): gets element I of array A -- xrefl.pl",
    "array_set(A,I,E): sets element I of array A -- xrefl.pl",
    "array_size(A,L): returns the number of elements of an array -- xrefl.pl",
    "array_to_list(A,Is): converts an array to a list -- xrefl.pl",
    "ask_engine(Engine,Query, Result): injects Query to into Engine, which, will react to it with engine_yield(Answer) -- engine.pl",
    "ask_inner_server(IServer,Answer): collects the answer from an inner server (and possibly waits until is done) -- xnet.pl",
    "ask_interactor(Interactor,Query): asks an Interactor a Query -- xbuiltins.pl",
    "ask_styla_engine(E,R): asks Styla engine E and returns answer term R -- styla.pl",
    "assert(C): adds clause C to the database -- db.pl",
    "asserta(C): adds clause C to the front of the database -- db.pl",
    "assertz(C): adds clause C to end of the database -- db.pl",
    "atom_codes(A,Cs): converts between an atom and a list of character codes -- shared.pl",
    "atom_concat(A,B,C): true if C is the concatenation of A and B -- shared.pl",
    "atom_length(Atom,Len): computes length L of an Atom -- shared.pl",
    "atom_to_term(A,T): reads term T from atom A -- xio.pl",
    "atom_to_term(A,T,Vs): reads term T + vars Vs from atom A -- xio.pl",
    "atomic_list_concat(As,A): A is the concatentation of atomic elements on list As -- xbuiltins.pl",
    "available_memory(M): computes memory still available - when reaching it Java crashes with OutOfMemory exception -- xbuiltins.pl",
    "bagof(X,Vs^G,Xs) : collects list of X such that G into Xs - it may backtrack if variables not in Vs occur in G or if Vs is absent -- bagof.pl",
    "bcompile(F): compiles F.pl to F.bp - including builtins and dynamics - it should include psrc/top.pl -- lfix.pl",
    "between(From,To, I) : generates integers I in [From..To] -- lib.pl",
    "bg(Goal,Hub): launches a background thread discarding all solutions of Goal. stop(hub) can be used to stop the thread -- xtask.pl",
    "bg_clone(Goal,Hub): launches a background thread discarding all solutions of Goal and cloning current symtable - use stop(Hub) to stop it -- xtask.pl",
    "bg_with(WamFileName,Goal,Hub): starts goal with code loaded from WamFileName -- xtask.pl",
    "bp_terms:: sets prolog_flag term_encoder in remote_run/run_server to send terms as strings that BinProlog can parse -- net.pl",
    "builtin/3: contains specs for builtins shared with C emulator -- builtins.pl",
    "call(FXs,A1,...AN) : calls a closure of the form FXs=F(X1..Xk) with A1..An appended afetr X1..Kk -- lib.pl",
    "callN(FXs,Ys): adds supplementary args from list Ys to closure FXs and call resulting goal -- lib.pl",
    "call_det(A,G,D): D is true if A is the last solution of a call to G -- iso.pl",
    "call_det(G, Det): succeeds if call(G) succeeds and unifies Det with true if G has no more solutions, with false otherwise -- engine.pl",
    "call_det(G,D): D is true if G is bound to the last solution of a call to G -- iso.pl",
    "call_ifdef(G,AltG) : if G is compiled calls G, otherwise calls AltG -- lib.pl",
    "call_java_class_method(ClassName,MethodAndArgs,Result): calls static Java method using <methodName>(A1,...An) syntax -- xrefl.pl",
    "call_with(Db,Body): metainterpreter, evaluates Body using clauses from database Db -- meta.pl",
    "call_with_time_limit(Secs,Goal): calls goal on a thread while watching that no more than Secs time is taken in which case it throws time_limit_exceeded -- xtask.pl",
    "cat_term_of(Cat,V-[Rank,Attr,Value,EdgesWithProps]): iterates over vertices V of a Cat graph -- graphs.pl",
    "cat_to_terms(Cat,Terms): converts a Cat graph to a list of (attributed) Terms of the form vertex-edges -- graphs.pl",
    "catch(Goal,Exception,OnException): if calling Goal throws E and E=Exception call OnException, otherwise throw E -- engine.pl",
    "cc0(Mode,C0): main compiler entry point -- lco.pl",
    "ccall(H,P,X,G,R): calls cserver at H:P with goal G and gets back R=the(X) or 'no' if it fails -- jlib.pl",
    "change_arg(I,T,New): replaces distructively _constant_ arg I of T with New. -- xbuiltins.pl",
    "char_code(Atom, Code): converts between character and character code -- shared.pl",
    "chdir(Dir), cd(Dir): changes (globally) current directory to Dir -- xio.pl",
    "clause(H,B): true if clause C=(H:-B) is in the database -- db.pl",
    "clean_up_publishing: removes everything published as well as tracking of subscribers -- publishing.pl",
    "clear_path: clears search path for find_file -- xbuiltins.pl",
    "close(Stream): closes stream -- xio.pl",
    "close_gui_printer(Name): close an output enabled GUI window -- gui.pl",
    "close_list(Bag,Xs): moves all elements of Bag to Prolog list Xs. Bag is still usable for new lis_adds. -- xbuiltins.pl",
    "code_of(File,C): backtracks over char codes in File -- xio.pl",
    "codes_words(Cs,Ws): parses/unparses list of codes to/from words -- xio.pl",
    "combines Xs and Ys into pairs X-Y with X in Xs and Y in Ys -- lists.pl",
    "compare(R,X,Y) : true if R (<,=,>) expresses the standard order between X,Y -- sort.pl",
    "compile(InFile,OutFile): compiles including builtins and dynamics - it should include psrc/top.pl -- lfix.pl",
    "compile_mt(Files,OutFile): compiles Files+built-ins concurrently and merges the results to a .bp file -- lfix.pl",
    "concat_atom(As,A): concatenates atoms on list As to A -- xlib.pl",
    "concatenate_files(Fs,F): concatenates list of files Fs to file F -- xbuiltins.pl",
    "console: starts a console - type exit to quit -- gui.pl",
    "consult(F): asserts all clauses if F to defaul database -- db.pl",
    "consume_new(Subscriber,Channel,Content): reads next message on Channel - Content expected to be a free variable -- publishing.pl",
    "coop_all(T,Ts): obtains the list Ts of all available terms matching T - cooperative, requires a coordinator -- coop_linda.pl",
    "coop_in(T): waits until T is available - cooperative, requires a coordinator -- coop_linda.pl",
    "coop_linda.pl: lightweight cooperative engine coordinator using Linda operations -- coop_linda.pl",
    "coop_out(T): makes T available - cooperative, requires a coordinator -- coop_linda.pl",
    "coordinate(Coordinator): coordinates a set of tascks performing coop_it/coop_out operations -- coop_linda.pl",
    "copy_term(T,CT): creates copy of term T with fresh variables -- engine.pl",
    "count_answers(Goal,Count): counts number of answers of a goal, efficiently -- lib.pl",
    "cputime(T): computes time since beginning of seesion in ms -- xbuiltins.pl",
    "crossref_warnings: prints crossref warning when compiling to memory -- lfix.pl",
    "ctr_add(Ctr,X):  adds value X to Ctr -- xbuiltins.pl",
    "ctr_dec(Ctr,X): decrements Ctr -- xbuiltins.pl",
    "ctr_get(Ctr,X): gets current value X of Ctr -- xbuiltins.pl",
    "ctr_inc(Ctr,X): increments Ctr -- xbuiltins.pl",
    "current_atom(A): backtracks over all atoms (warning: it also keeps them alive!) -- xrefl.pl",
    "current_compiled(F/N): backtracks over all compiled predicates -- xrefl.pl",
    "current_dir(D): returns current directory -- xbuiltins.pl",
    "current_dynamic(F/N): backtracks over all dynamic predicates -- xrefl.pl",
    "current_engine(Handle) : returns Handle (a small int) representing current engine as seen by its parent -- builtins.pl",
    "current_input(Stream) : returns current input stream -- xio.pl",
    "current_non_atom(A): backtracks over all unusual symbols - engines, bignums, other Java objects etc. -- xrefl.pl",
    "current_op(Pri,Assoc,Op): lists/checks what current operators are in effect -- xbuiltins.pl",
    "current_output(Stream): returns current output stream -- xio.pl",
    "current_predicate(F/N) : true if predicate F/N is compiled or has a definition in the database -- xrefl.pl",
    "current_prolog_flag(F,X): sets Prolog flag -- xlib.pl",
    "current_symbol(Sym): gets the list of all atoms from the symbol table - note that it also means it keeps them alive! -- xbuiltins.pl",
    "current_system_symbol(Sym): iterates over all atoms from the symbol table that are part of the system -- xbuiltins.pl",
    "current_user_symbol(Sym): iterates over all atoms from the symbol table created by the user -- xbuiltins.pl",
    "db_assert, db_retract etc: same as assert, retract but extra first argument names a database on which they act -- db.pl",
    "db_clear(Db) : clears all caluses of database Db -- db.pl",
    "db_clear: removes all clauses from database -- db.pl",
    "db_consult(InFile,Db) consults InFile to database named Db -- db.pl",
    "db_dynamic, db_is_dynamic, db_abolish : same as their counterparts wihtouh 'db_', except that extra first argument names a database on which they act -- db.pl",
    "db_ensure_bound(Db) - generates, if argument Db is unbound, '$0', '$1', .. as Db name -- db.pl",
    "db_reconsult(InFile,Db) reconsults InFile to database named Db -- db.pl",
    "db_save(Db,F): saves database Db to plain text file F (with no guaranty that it can be read back!) -- db.pl",
    "db_save_canonical(Db,F): saves database Db to plain text file F (with guaranty that it can be read back!) -- db.pl",
    "default_port (ServerPort): returns default server port -- xnet.pl",
    "default_styla_engine(E): the default Styla engine E e.g. in which asserts persist -- styla.pl",
    "delete_directory(D): deletes a directory in current directory -- xbuiltins.pl",
    "delete_file(F): deletes a file in current directory -- xbuiltins.pl",
    "det_call(G): signals error if G has more than one answer -- compat.pl",
    "digest_prolog_files(PrologFiles,OldRootWamFile,NewRootWamFile): extends bootable root wamfile with a list of prolog files -- xlib.pl",
    "dir_or_file(DorF,Dir,X): iterates over directories (when DorF=0) or files (when DorF=1) in Dir -- xbuiltins.pl",
    "dirs(Dir,Ds): collects list Ds of direcories in Dir -- xbuiltins.pl",
    "dirs(Ds): collects list Ds of direcories in current directory -- xbuiltins.pl",
    "discards the arguments received on the command line -- xbuiltins.pl",
    "display(Term): displays a term in a canonical form -- xio.pl",
    "dq_add/3, dq_remove/3, dq_is_empty/1: difference list queue operations -- engine.pl",
    "drop(N,Xs,Ys): drops the first N elements of list Xs and returns the left over elements Ys -- lists.pl",
    "drop_at_least(N,G): drops at least the first N answers of G -- compat.pl",
    "dynamic(F/N): ensures predicate F/N will is dynamic - it is ok to call such predicates even if none has been asserted -- db.pl",
    "element_of(Interactor,X): backtracks over all answers returned by Interactor (possibly an engine) -- engine.pl",
    "engine_yield(Answer): reacts to ask_engine(Engine,Query, Result) by calling from_engine and then returning Answer -- engine.pl",
    "ensure_number(Num,MaybeBignum): converts, if needed string or $number(N) to BigInteger or BigDecimal -- xbuiltins.pl",
    "entry point in Prolog interactive loop -- xtop.pl",
    "entry point in a module, in particular 'main' -- xtop.pl",
    "errmes(Message,Culprit): generates error message -- engine.pl",
    "exists_absolute(FileOrDir): true if FileOrDir is or expands to an existing file or dir -- xbuiltins.pl",
    "exists_dir(D): true if directory D exists -- xbuiltins.pl",
    "exists_file(F): true if file or dir F exists -- xbuiltins.pl",
    "expand_term(T,ExpandedT): applies term_expansion/2 if defined as a dynamic, possibly DCG expansion otherwise -- dcg.pl",
    "external_engine(Source,E): creates new code space + engine from a *.bp file or reader -- xlib.pl",
    "external_engine(WamSource,X,G,E) : creates external engine E with separate code space and goal X,G -- xlib.pl",
    "false: same as fail, fails always -- shared.pl",
    "fcompile(FName): compiles FName.pl to FName.wam - including dynamics -- lfix.pl",
    "file compat.pl: various backward comaptibility extensions -- compat.pl",
    "file_from_jar(JarName,FileNameInJar,NewFileName): extracts a file from a .jar container -- compat.pl",
    "file_iterator(AbsolutFileName): returns all absolute file names reachable from current dir -- sys.pl",
    "file_iterator(TopDir,Path,F,AbsolutFileName): returns files reachable fro current dir -- sys.pl",
    "files(Dir,Fs): collects list Fs of files that are not directories in Dir -- xbuiltins.pl",
    "files(Fs): collects list Fs of files that are not directories in current directory -- xbuiltins.pl",
    "find_at_most(N,X,G,Xs): collects, like, findall, at most K answers X of G to Xs -- compat.pl",
    "find_file(Prefs,File,Sufs,NewFile): finds File with name prefixed and suffixed as NewFile -- xio.pl",
    "find_free_port(BasePort,MaxTry,FreePort): tries to find free port starting from BasePort up to BasePort+MaxTry -- xnet.pl",
    "find_free_port(P): finds a free port starting from 500 and trying out the next 100 ports -- xnet.pl",
    "find_while(C,X,G,Xs): answer_stream to list converters -- compat.pl",
    "findall(X,G,Xs): collects to a list Xs copies of all answers X of G using engines -- engine.pl",
    "findall(X,G,Xs,End): collects to a list Xs copies of all answers X of G concatenated with list End -- engine.pl",
    "first_on_path(Dir): returns first directory on search path for find_file -- xbuiltins.pl",
    "float_fractional_part(X,Y): gets the fractional part of a float number -- xbuiltins.pl",
    "float_integer_part(X,Y): gets the integer part of a float number -- xbuiltins.pl",
    "foldall(F,X^Generator,R): combines 2 by 2 answers X of Generator, by applying closure F -- engine.pl",
    "foldl(F,Z,Xs,R): combines with F all members of Xs, from left to right, starting with Z -- lists.pl",
    "foldl(F,Z,Xs,R): combines with F all members of Xs, from right to left, starting with Z -- lists.pl",
    "for(I,A,B): generates ints I in [A..B] -- xlib.pl",
    "forall(G1,G2): true if forall G1, G2 -- shared.pl",
    "foreach(When,Then) : evaluates once(Then) for each success of When (works by its side effects) -- shared.pl",
    "from_engine(Term) : retrieves Term sent to this Engine -- builtins.pl",
    "from_file(F,T): loads (large term T, possibly containing serilizable Java objects) from file F -- xbuiltins.pl",
    "from_linear(CT,T): converts a term back to normal Prolog representation -- cserver.pl",
    "from_set(Set,Xs): converts set to List of ground elements -- xbuiltins.pl",
    "fun(F,N,T): creates term T of arity N with function symbol F -- builtins.pl",
    "functor(T,F,N): extracts F/N from F(X1...XN) and/or creates aterm with arity N and function symbol F -- lib.pl",
    "gensym(S,X): generates news symbols on ecah call X=S1,X=S2... etc -- xbuiltins.pl",
    "gensym_no(Base,N): gets next N associated to symbol Base - local to symbol table -- xbuiltins.pl",
    "get(Interactor,Result) : collects a result computed by an Interactor (an engine in particular) -- engine.pl",
    "get_alias(Stream,Alias): when at least one is nonvar it returns the other -- xio.pl",
    "get_cmd_line_args(Terms): returns the list of arguments received on the command line -- xbuiltins.pl",
    "get_code(C): reads a char code from current input stream -- xio.pl",
    "get_code(I,C): reads a char code from interactor/input stream I -- xio.pl",
    "get_date_time(DateString): gets current date and time as formatted string -- xlib.pl",
    "get_encoding(Encoding): gets char encoding -- xlib.pl",
    "get_java_class(O,Class): get the a handle to the class to which object O is an instance -- xrefl.pl",
    "get_java_class_field(ClassName,FieldName,Val): gets the content Val of a (public) static Java field -- xrefl.pl",
    "get_java_field(Object,FieldName,Val): get the content Val of a (public) Java field -- xrefl.pl",
    "get_java_field_handle(Obj,FieldName,FieldHandle): returns handle to FieldName in object Obj -- xbuiltins.pl",
    "get_supers(X,Supers): gets the list of agents that X follows in this space -- meta.pl",
    "get_system_property(Name,Prop): gets system proprty - if var(Name) it backtracks over all -- xio.pl",
    "get_time(TimeFrom1970ms): get time from 1970 Jan 1 in miliseconds -- xlib.pl",
    "getenv(Key,Value): gets an environment variable -- xbuiltins.pl",
    "global_gensym(S,X): generates news symbols on ecah call X=S1,X=S2... etc - global to process -- xbuiltins.pl",
    "global_gensym_no(Base,N): gets next N associated to symbol Base - global to process -- xbuiltins.pl",
    "ground(X): true if X contains no unbound variables -- lib.pl",
    "ground_set_difference(As,Bs,Cs): computes the set difference without duplicates of ground As,Bs -- xbuiltins.pl",
    "ground_set_union(As,Bs,Cs): computes the set intersection without duplicates of ground As,Bs -- xbuiltins.pl",
    "ground_set_union(As,Bs,Cs): computes the set union without duplicates of ground As,Bs -- xbuiltins.pl",
    "gvar(V): backtracks over names of all global vars V -- xbuiltins.pl",
    "gvar_get(Var,Val): gets Val of global Var as in Var ==> Val -- xbuiltins.pl",
    "gvar_remove(Var): removes a global variable -- xbuiltins.pl",
    "gvar_set(Var,Val): sets global Var to Val as in Var <== Val -- xbuiltins.pl",
    "gvars(Vs): gets list of all gvars -- xbuiltins.pl",
    "gvars: lists all gvars and their values -- xbuiltins.pl",
    "hkey(Mod,T,N): computes for nonvar term T a shallow hash key N in 0..Mod-1 -- xbuiltins.pl",
    "hub(H): creates a hub - an interactor used to synchronize threads -- xbuiltins.pl",
    "i_call(S,G): runs goal G on inner server S -- xnet.pl",
    "i_call(S,X,G,R): runs G on inner server S returning R=the(X) or no if it fails -- xnet.pl",
    "i_connection(S,C): opens a connection C to an i_server S -- xnet.pl",
    "i_halt(S): stops inner server with handle S -- xnet.pl",
    "i_run_at(C,G): runs goal G at connection C on inner server -- xnet.pl",
    "i_run_at(C,X,G,R): runs goal G at connection C on inner server returns R=the(X) or no if it fails -- xnet.pl",
    "i_server(BPFile,Goal,Handle): runs inner server initialize with Goal, based on alternate *.bp file as starting point -- xnet.pl",
    "i_server(Goal,S): runs inner server S after initial Goal run in the context of the inner server -- xnet.pl",
    "i_server(S): creates internal emulation of socket server - returns handle S instead of running on a port -- xnet.pl",
    "i_stop(C): stops innter server at connection C -- xnet.pl",
    "icall, icall_op, icall_impure: bridges to fast internal builtins called directly from emulator -- builtins.pl",
    "if_any(Cond,Then,Else) for each success of Cond evaluates Then, but if Cond just fails Else is called -- engine.pl",
    "included_file_of(File,Included): iterates over all files included with statemts of the form :-[F1,...Fn] in File -- xio.pl",
    "index(Spec): indexes arg positions marked 1 in Spec ; index implies dynamic as it only indexes dynamics -- db.pl",
    "init(Xs,AllButLast): returns all but the last element of a list -- lists.pl",
    "init_publishing(ContentIndexings): sets up indexing using list of ContentIndexings of the form pred(1/0,1/0...) -- publishing.pl",
    "init_publishing: sets up default initial assumptions for publishing -- publishing.pl",
    "inner_server_loop(In,Out): loops consuming data from hub In and returning answers to hub Out -- xnet.pl",
    "int_sqrt(N,R): computes integer square root R of N, using Newton's method -- xbuiltins.pl",
    "interactor(T): recognizes type of an interactor -- lib.pl",
    "invoke_array_method(MethodAndArgs,R): calls static Array class methods -- xrefl.pl",
    "invoke_java_method(Cls,Obj,MethName,Args,Answer): invokes a java method in class Cls on Object Obj -- xbuiltins.pl",
    "invoke_java_method(ObjectOrClass,MethodName,Result) : calls Java method using <methodName>(A1,...An) syntax -- xrefl.pl",
    "is_agent(X): checks or bactracks over all agents in this space -- lagent.pl",
    "is_compiled(F(X1..XN)) : true if F/N it is a compiled predicate -- builtins.pl",
    "is_dir(D): true if D is a subdirectory in current directory -- xbuiltins.pl",
    "is_dynamic(H): checks if a predicate H=F(X1..Xn) is dynamic -- db.pl",
    "is_engine(E) : true if E is an engine -- engine.pl",
    "is_false(B): checks if a Boolean returned by Java represents false -- xrefl.pl",
    "is_file(F): true if F is a file in current directory -- xbuiltins.pl",
    "is_interactor(E) : true if E is an interactor (LogicInteractor - a kind of engine , in particular) -- engine.pl",
    "is_list(X): true if X is instantiated to a list -- lists.pl",
    "is_prolog(Prolog): tells which Prolog is this: returns lprolog -- xtop.pl",
    "is_quoted_number(N): recognizes that N is a quoted number like '1111'. This information is optimized away by the compiler. -- shared.pl",
    "is_space(Host,Space): true if Space is registered at Host -- lagent.pl",
    "is_true(B): checks if a Boolean returned by Java represents true -- xrefl.pl",
    "java_profiling(off) turns off Java method profiling -- xbuiltins.pl",
    "java_profiling(on) turns on Java method profiling -- xbuiltins.pl",
    "java_terms:: sets prolog_flag term_encoder in remote_run/run_server such that serialized terms are sent - avoiding parsing -- net.pl",
    "keygroup(KsVs,Keys,Vals): keysorts KsVs, then backtrack over groups of the form Key,Vals -- sort.pl",
    "keysort(KVs,NewKVs): sorts by keys, a list of Key-Value pairs -- sort.pl",
    "kill_my_process(Process): kills process started with system/5 -- sys.pl",
    "last(Xs,X): picks X, the last element of list Xs -- lists.pl",
    "lazy_drop(N): to be used with DCGs - drops first N of lazy stream, advances if needed -- engine.pl",
    "lazy_findall(X,G,LazyList): creates LazyList to be explored using DCG syntax with lazy_take,lazy_drop etc. -- engine.pl",
    "lazy_get_state(Xs) : to be used with DCGs - gets current lazy stream -- engine.pl",
    "lazy_head(X): to be used with DCGs - gets head X of lazy stream, advances if needed -- engine.pl",
    "lazy_set_state(X,G): used with DCGs - sets stream to L such that X:G~>L. -- engine.pl",
    "lazy_tail: to be used with DCGs - consumes head of lazy stream, advances if needed -- engine.pl",
    "lazy_take(N,Xs): to be used with DCGs - gets first N of lazy stream as Xs, advances if needed -- engine.pl",
    "lco: bootstrapping - self compiles by compiling ../psr/top.pl to ../bin/wam.bp -- lfix.pl",
    "length(Xs,L): true if the length of list Xs is L - generates Xs if needed -- lib.pl",
    "line_codes_of(File,Cs): backtracks over lines seen as lists of char codes in File -- xio.pl",
    "line_of(File,C): backtracks over lines in File -- xio.pl",
    "list_to_array(Xs,A): converts a list to an array -- xrefl.pl",
    "listing(Db,F/N): lists predicate F/N in database Db -- db.pl",
    "listing: list all clauses from default database -- db.pl",
    "listings: list clauses from all databases -- db.pl",
    "load(Name): loads the set of datbases from a saved snapshot Name.px -- db.pl",
    "log(Mes): sends Mes + timestamp (usually something wrong) to the logger -- xlib.pl",
    "log_to(Fname,Mes,WithStamp): if WithTimeStamp>0 appends <<< tamp >>> + Mes to Fname -- xlib.pl",
    "lprolog(Dir,Args0,Output): launches an lprolog process in Dir, with Args - it is assumed the user will halt it remotely -- sys.pl",
    "lprolog(Wait,Dir,Args,FinalCmd, Process,Output): runs new lean Prolog process in Dir and returns the Process id and its Output if Wait>0 -- sys.pl",
    "ls: (also dir) lists current directory -- xbuiltins.pl",
    "lsb(N,B): B is the index of the lowest set bit of N>0 -- xbuiltins.pl",
    "make_directory(D): makes a directory in current directory -- xbuiltins.pl",
    "maplist(F,Xs1,Xs2,...): applies F to elements in the same position in Xs1,Xs2.. -- lists.pl",
    "max_cores(M): returns the maximum numbers of CPUs available to this JVM as seen by the OS -- xbuiltins.pl",
    "max_memory(M): returns max memory in Mbytes available to this Java VM -- xbuiltins.pl",
    "mbg(Goals):: launches Goals in parallel and waits until all of them terminate - note this ignores the answers they produce -- xtask.pl",
    "mbg(Tasks,Result): launches a list of tasks [...(X:-G)...] on independent threads and collects their results X one at a time -- xtask.pl",
    "mbg/2 example: ?- mbg([(I:-for(I,1,3)),(J:-member(J,[a,b]))],R). % note - similar to multi_all/2, except that in iterates -- xtask.pl",
    "mmap_get(D,X,A): returns an A associated to key X in multi-map D - backtracks if X unbound -- xlib.pl",
    "mmap_put(D,X,A): adds A to key X in multi-map D -- xlib.pl",
    "mmap_remove(D,X): removes all values associated to key X in multi-map D -- xlib.pl",
    "mmap_remove(D,X,A): removes specific A associated to key X in multi-map D -- xlib.pl",
    "msb(N,B): B is the index of highest set bit of N>0 -- xbuiltins.pl",
    "mset_* ... : operations similar to ord_* .. but on multisets (calls msort/2 first) -- sort.pl",
    "mset_distance(Xs,Ys,R): computes a distance between multisets in N*log(N) time -- sort.pl",
    "mset_sum(Xs,Ys,Zs):  multiset sum (disjoint union) -- sort.pl",
    "msort(Xs,SortedMultisetXs): sorts a list without removing duplicates -- sort.pl",
    "multi_all(XGs,Xs): runs list of goals XGs of the form Xs:-G ant collects all answers to a list -- xtask.pl",
    "multi_all(XGs,Xs): runs list of goals XGs of the form Xs:-G ant collects all answers to a list -- xtask.pl",
    "multi_best(F,XGs,M): runs list of goals XGs of the form N:-G where N is a number and extracts the max M -- xtask.pl",
    "multi_findall(XGs,Xss): for each (X:-G) it runs in parallel a findall(X,G,Xs) goal and collects a list of list of answers Xss -- xtask.pl",
    "multi_first(K,XGs,Xs): runs list of goals XGs of the form Xs:-G until the first K answers Xs are found - or fewer if less then K -- xtask.pl",
    "multi_first(XGs,X): runs list of goals XGs of the form Xs:-G until a first answer X is found -- xtask.pl",
    "multi_fold(F,XGs,Xs): runs list of goals XGs of the form Xs:-G and collects all answers to a list -- xtask.pl",
    "nb_setarg(I,T,New): replaces distructively _constant_ arg I of T with New. -- xbuiltins.pl",
    "new_array(ClassName,Dim,Array): makes a new array to hold Dim elements from class ClassName -- xrefl.pl",
    "new_coordinator(Db): creates a new coordinator using database Db (or synthetic name if var) -- coop_linda.pl",
    "new_ctr(Ctr): creates a new couter initialized at 0 -- xbuiltins.pl",
    "new_engine(Engine,X,G): loades an engine with goal G returning instance of 'the'(X) or 'no' as answer -- engine.pl",
    "new_engine(X,G,Engine): creates engine with goal G returning instance of 'the'(X) or 'no' as answer -- engine.pl",
    "new_inner_server(IServer): creates an inner server consisting of thread and 2 hubs -- xnet.pl",
    "new_interactor(Class,Initializer,Handle): creates a new Interactor from and Intractor Class -- xbuiltins.pl",
    "new_java_class(Name,Cls): returns handle to (public) Java class Cls from Name (package included!) -- xbuiltins.pl",
    "new_java_object(ClassAndArgs,Object): makes new Java Object from Class -- xrefl.pl",
    "new_java_object(Cls,Args,Obj): calls a Java constructor with Args on Cls and returns a handle Obj -- xbuiltins.pl",
    "new_logic_thread(Hub,X,G): a new logic thread, sharing this symbol table is created - disables SYMGC -- xbuiltins.pl",
    "new_logic_thread(Hub,X,G,Clone,Source): creates a new thread by Cloning current Prolog or loading new Prolog from Source -- xbuiltins.pl",
    "new_mmap(D): creates a new multi-map dictionary with one or more values associated to each key -- xlib.pl",
    "new_styla_engine(E): creates a new Styla engine E -- styla.pl",
    "new_task(Coord,G): adds a new task to a coordinator Db -- coop_linda.pl",
    "newer_file_of(F1,F2,Newer): pick newer file among F1 and F2 -- xbuiltins.pl",
    "next_of(NextIterator,E): generic iterator interface - assuming it implements next() returning null at end -- xrefl.pl",
    "nl(Stream): writes newline to stream -- xio.pl",
    "nth1(N,Xs,X): picks N-th element X starting from 1 occuring in Xs -- lists.pl",
    "nth_answer(N,G): gives only the N-th answer of G -- compat.pl",
    "number_chars(Number, List) succeeds when List is a list whose elements are the one character atoms that in order make up Number. -- shared.pl",
    "number_codes(A,Cs): converts between an number and a list of character codes -- shared.pl",
    "numbervars(T,N0,N): Replaces free vars with '$VAR'(N) starting from N0 ending with N that is computed -- lib.pl",
    "numlist(Min,Max,Ns): generates list of ints between Min and Max -- xlib.pl",
    "object_to_quoted_string(T,S): converts a term T to a symbol such that it can be read back -- xbuiltins.pl",
    "open(File,Mode,Stream): opens a file in given mode, returning a stream -- xio.pl",
    "open_gui_printer(Name): opens an output enabled GUI window -- gui.pl",
    "open_list(Bag): creates a persistent list -- xbuiltins.pl",
    "ord_intersection/3: computes the intersection of two orderd sets -- sort.pl",
    "ord_subset/2: checks if the first ordered set is included in the second -- sort.pl",
    "ord_subtract/3, ord_difference/3: computes the difference of two ordered sets -- sort.pl",
    "ord_sym_difference/3 computes the symmetric difference of two ordered sets -- sort.pl",
    "ord_union/3: computes the union of two orderd sets -- sort.pl",
    "os_name(OS): return OS -- xio.pl",
    "other_object(T): recognizes type of some Java objects other than engines, interactors etc. -- lib.pl",
    "parse_tokens(Ts,Vs,L1,L2,Term): parses tokens into term writes out syntax eror from L1 to L2 if fails to -- xio.pl",
    "partition(Pred, Xs, Included, Excluded): separates Xs in two lists using Pred -- lists.pl",
    "path_element(P): backtracks over path elements P -- xio.pl",
    "path_elements(Dirs): returns the list of directories in search path -- xbuiltins.pl",
    "peek_at_published(ContentPattern, Matches): searches for published content independently of having read it alredy -- publishing.pl",
    "picks N-th element X starting from 0 occuring in Xs -- lists.pl",
    "pop_from_path(Dir): removes Dir from beginning of search path for find_file -- xbuiltins.pl",
    "pops a command line argument as the(StringArgument) or 'no' if none is left -- xbuiltins.pl",
    "predicate_property(Pred,Prop): true if Pred=F(X1...Xn) has property Prop -- xrefl.pl",
    "println(T): prints term T + nl to cirrent output -- xio.pl",
    "prodlist(Xs,P): returns P, the product of numbers on list Xs -- lists.pl",
    "protect_engine(S): makes sure engine S is never garbage collected -- xbuiltins.pl",
    "publish(Channel,Content): -- publishing.pl",
    "publishing API: induces no suspension - can be used with s_call and open_dialog, close_dialog -- publishing.pl",
    "push_to_path(Dir): ads Dir to beginning of search path for find_file -- xbuiltins.pl",
    "put_code(Stream,C): write character of given code to stream -- xio.pl",
    "pwd: prints out current directory -- xbuiltins.pl",
    "qcompile(File) : when used from Java cmd line acts like if compile(File) was typed at '?-' prompt -- lfix.pl",
    "random(Lim,Var) return random integer in 0..Lim-1 -- xbuiltins.pl",
    "read(Stream,Term): reads term from Stream -- xio.pl",
    "read(Stream,WarnSingletons, Term,Vs): reads term from Stream as well as list of variables with names -- xio.pl",
    "read(Term): reads term from current input - a line at time when from console -- xio.pl",
    "read_string(I,S): reads from interactor I, a line as a symbol without printing any prompt -- xio.pl",
    "read_string(S): reads from current input, a line as a symbol without printing any prompt -- xio.pl",
    "read_term(Stream,Term,Options): reads term from Stream according to Options - e.g [singleton(warning)] -- xio.pl",
    "read_term(Stream,WarnSingletons, Term,Vs,Line1,Line2): reads a term from a stram and if WarnSingletons=yes warns accordingly -- xio.pl",
    "read_term(Term,Options): reads term from current input according to Options - e.g [singleton(warning)] -- xio.pl",
    "read_words(Stream,Words): reads words from stream -- xio.pl",
    "readln(T): reads line from current input stream -- xio.pl",
    "reconsult(F):cleans defautl database and then asserts all clauses if F to defaul database -- db.pl",
    "reconsult_string(String): reconsults clauses by parsing string -- gui.pl",
    "remdup(Multiset,Set) : removes duplicates from a sorted list Multiset -- sort.pl",
    "remote_ping(Host,Port) : true if classic server at Host,Port is up and running -- net.pl",
    "remote_run(H,P,G): runs G remotely on classic server at H,P - beware that it only handles small data !!! -- net.pl",
    "remote_run(H,P,X,G,R): runs a G remotely on classic server at H,P return R=the(X) or no if it fails -- net.pl",
    "remote_wait(Host,Port): waits until server on Host:Port is on -- net.pl",
    "remove_alias(StreamOrAlias) -- removes the alias if the stream or the alias are given -- xio.pl",
    "remove_val(Sym): removes attribute of symbol Sym -- xbuiltins.pl",
    "rename_file(Old,New): renames a file -- xbuiltins.pl",
    "reset_gensym(Base): resets gensym asocciated to base -- xbuiltins.pl",
    "reset_global_gensym(Base): resets gensym asocciated to base - global to process -- xbuiltins.pl",
    "retract(H): retracts clauses with head unifying with H from the database, one at a time -- db.pl",
    "retract1(H): retracts (at most) one clause with head unifying with H from the database -- db.pl",
    "retractall(H): retracts all clauses with head unifying with H from the database -- db.pl",
    "returns random integer in [0..1] -- xbuiltins.pl",
    "reverse(Xs,Ys) : Ys is Xs reversed -- lists.pl",
    "rli_consume(Subscriber,Host,Channel,Content): consumes Content throug RLI as Subscriber -- publishing.pl",
    "rli_peek_at_published(Host,Channel,ContentPattern, Matches): associatively finds all matching patterns on Channel -- publishing.pl",
    "rli_publish(Host,Channel,Content): publishes Content on Channel at Host -- publishing.pl",
    "rli_start_publishing(Channel,ContentIndexings): starts RLI enabled publishing -- publishing.pl",
    "rselect/3: like select/3 but starts with the last one -- lists.pl",
    "run concurrently all tasks in current task group -- xtask.pl",
    "run_server(Port): starts classic server on Port -- net.pl",
    "run_tasks(TG,Result): runs all tasks in group TG and collects all results one a time ; it fails when no results are left -- xtask.pl",
    "s_call(Host,Port,X,G,R): remote call to Host:Port to run G returning R= the(X), no or exception -- xnet.pl",
    "s_connection(Host,Port,Connection): opens socket Connection to Host:Port -- xbuiltins.pl",
    "s_disconnect(Connection): closes socket connection -- xbuiltins.pl",
    "s_halt(Host,Port): halts server -- xnet.pl",
    "s_halt_at(Connection): halts the process hosting the server on Connection -- xnet.pl",
    "s_ping(Host,Port): tests if server on Host:Port is on -- xbuiltins.pl",
    "s_run_at(Connection,X,G,R): remote call on Connection to run G returning the(X), no or exception -- xnet.pl",
    "s_server(Port,BPFile,Goal): starts socket server on Port and runs Goal on it using compiled BPFile -- xnet.pl",
    "s_server(Port,Goal): starts socket server on Port and runs Goal on it -- xnet.pl",
    "s_stop(Host,Port): stops server at Host:Port without halting the process in which it runs - broken -- xnet.pl",
    "s_stop_at(Connection): stops the server on Connection -- xnet.pl",
    "s_wait(Host,Port): waits until server on Host:Port is on -- xnet.pl",
    "save(Name): saves a snapshot of all databases to file Name.px -- db.pl",
    "select(X,Xs,Ys) : pulls out an element X from list Xs returning the others as Ys -- lists.pl",
    "select_nonvar/3: like select/3 but checks that list ends in a nonvar -- lists.pl",
    "sentence_of(F,ListOfWords): bactkracks over sentences terminated with .!? in a file returning ListOfWords -- compat.pl",
    "set_alias(Stream,Alias): binds Stream and Alias together -- xio.pl",
    "set_distance(Xs,Ys,R): computes a distance between sets in N*log(N) time -- sort.pl",
    "set_encoding(Encoding): sets char encoding -- xlib.pl",
    "set_format_precision(DecimalDigits): sets precision of decimal printouts -- xbuiltins.pl",
    "set_input(Stream) : sets current input stream -- xio.pl",
    "set_java_class_field(ClassName,FieldName,NewVal): sets a static field of a named class to NewVal -- xrefl.pl",
    "set_java_field(Object,FieldName,NewVal) : sets the content of a (public) Java field to NewVal -- xrefl.pl",
    "set_output(Stream): sets current output stream -- xio.pl",
    "set_precision(DecimalDigits): sets precision of decimal computations -- xbuiltins.pl",
    "set_prolog_flag(F,X): sets Prolog flag -- xlib.pl",
    "set_quickfail(V,OldV): sets flag forcing quick failure (if higher) -- xlib.pl",
    "set_random_seed(IntSeed): sets random seed -- xbuiltins.pl",
    "set_symgc_force(Bits): forces symbol grabage collection if more than 2^Bits syms are present -- xbuiltins.pl",
    "set_verbosity(V,OldV): sets flag controlling verbosity (higher) of error messages -- xlib.pl",
    "setof(X,Vs^G,Xs) : collects set of X such that G into Xs - it may backtrack if variables not in Vs occur in G or if Vs is absent -- bagof.pl",
    "shm_put(F,S,V), shm_get(F,S,V) shm_remove(F,S): puts, gets, removes value V in shared memory dir F of shared var S -- xbuiltins.pl",
    "show_hfun(F,N): if F is a wf N->[N] function in draws the recursive unfolding graph of N with nordered edges -- graphs.pl",
    "show_hset(F,N): if F is a wf N->[N] function in draws the recursive unfolding graph of N withn unordered edges -- graphs.pl",
    "show_unpair(F,N): if F is unpair(Z,X,Y) is a wf unpairing function in draws the recursive unfolding graph of N -- graphs.pl",
    "show_unpair1(F,N): if F is unpair(Z,X-Y) is a wf unpairing function in draws the recursive unfolding graph of N -- graphs.pl",
    "sign(N,S): computes signum of N (-1,0,1) as in S is sign(N) -- xbuiltins.pl",
    "sleep_ms(Ms): sleeps a number of miliseconds, approximately -- xbuiltins.pl",
    "sleep_ns(Ms): sleeps a number of miliseconds, approximately -- xbuiltins.pl",
    "sort(Xs,SortedSetXs): sorts a list then removes duplicates -- sort.pl",
    "split_at(N,Xs,Ys,Zs): splits into first N elements Ys of list Xs and other elements Zs (if any) -- lists.pl",
    "split_to_groups(K,Xs,Xss): splits Xs into a list of K lists -- lists.pl",
    "split_to_size(K,Xs,Xss): splits Xs into a list of lists of size K or less each -- lists.pl",
    "start_space(BrokerHost,ThisHost,Port): starts an RLI service seen as associated to a space and registers it -- lagent.pl",
    "start_space(Port): starts and registers locally an RLI service seen as associated to a space -- lagent.pl",
    "statistics: prints out stats about various data areas -- xlib.pl",
    "stdio(I): returns standard input/output - an interactor usable as both streams -- xio.pl",
    "stop(E): stops an Interactor (an engine in particular) -- engine.pl",
    "stop: stops current engine -- engine.pl",
    "stop_coordinator(C): stops a coordinator and cleans all realated resources - engines, unconsumed data etc. -- coop_linda.pl",
    "stop_inner_server(IServer): stops an inner server -- xnet.pl",
    "stop_interactor(Interactor): stops an interactor -- xbuiltins.pl",
    "stop_s_console(H,P): stops s_console at H,P -- gui.pl",
    "stop_s_console(P): stops s_console on this host at P -- gui.pl",
    "stop_styla_engine(E): stops Styla engine E -- styla.pl",
    "stop_tasks tries to release tasks in default task group by stopping its Hub -- xtask.pl",
    "stops an i_server -- xnet.pl",
    "styla_engine_set_goal(E,A,G): sets goal term G and answer pattern A for E -- styla.pl",
    "styla_engine_set_goal_string(E,G): sets string G to be parsed as goal for E -- styla.pl",
    "styla_once(X,G,R): calls goal G and applies Styla's bindings to G -- styla.pl",
    "styla_once(X,G,R): collects all Styla answers from E running goal G -- styla.pl",
    "styla_once(X,G,R): collects first Styla answer from E running goal G -- styla.pl",
    "sub_atom(Atom, Before, Length, After, Sub_atom): true if Sub_atom is in Atom of length Length with Before characters preceding it and After characters following it. -- shared.pl",
    "sub_list(Cs, Before,Length,After, Xs): true if Cs is a list of length Length with Before elements preceding it and After elements following it. -- shared.pl",
    "sub_string/5: same as sub_list/5 -- shared.pl",
    "sublist_of_length(K,Xs,Ys): generates sublists of Xs of length K -- sort.pl",
    "subst_atom(Old,New,In,Out): replaces Old with New in atom In -- xbuiltins.pl",
    "succ(N,N1) : computes N1 successor of N -- builtins.pl",
    "sumlist(Xs,S): returns S, the sum of numbers on list Xs -- lists.pl",
    "symgc: force symbol garbage collection now -- xbuiltins.pl",
    "symgc_off: turn off automatic symbol grabage collection -- xbuiltins.pl",
    "symgc_on: turn on automatic symbol grabage collection -- xbuiltins.pl",
    "system(Cmd): calls an operating system command Cmd !!! BUGGY -- xbuiltins.pl",
    "system(Dir,CmdList, Output,RetCode): launches command in Dir waits until it finishes and returns its Output -- sys.pl",
    "system(Dir,CmdList,Wait, Process,Output,RetCode): launches new OS Process in Dir and returns the Process id to be used by kill_my_process/1 -- sys.pl",
    "tab(Stream,N): writes N spaces to Stream -- xio.pl",
    "take(N,Xs,Ys): takes the first N elements Ys of list Xs -- lists.pl",
    "take_at_most(N,G): generates at most the first N answers of G -- compat.pl",
    "tell(File), told, telling(File) : direct output to given file (deprecated) -- xio.pl",
    "tell_inner_server(IServer,X,G): gives a task that the server starts executing -- xnet.pl",
    "tell_interactor(Interactor,Task): tells Interactor about a Task to be done next time -- xbuiltins.pl",
    "term_expansion(Term,NewTermOrList): if defined as a dynamic predicate, this is called by expand_term/2 to rewrite Term to NewTermOrList -- dcg.pl",
    "term_of(File,Term): scans recursively over files following ':-[File].' commands for terms -- xio.pl",
    "term_of_string(S,T,Vs): backtracks over all terms T with vars Vs read from string S -- xio.pl",
    "term_to_atom(T,A): writes out term T to atom A -- xio.pl",
    "term_variables(Term,Vars) :: extracts set of free variables occurring in Term -- bagof.pl",
    "throw(E): throws an exception E -- engine.pl",
    "time(Goal): execute once(Goal) and prints time -- shared.pl",
    "time(Goal,T): execute once(Goal) and return time T -- shared.pl",
    "timed_call(MSecs,(Answer:-Goal),Result): calls goal on a thread running for no more than MSecs and returns the(Answer),time_limit_exceeded or no -- xtask.pl",
    "timed_call(Secs,Goal): calls goal on a thread while watching that no more than Secs time is taken in which case it fails -- xtask.pl",
    "timed_s_wait(MaxWait,Host,Port): waits up to MaxWait ms until server on Host:Port is on -- xnet.pl",
    "to test assumption grammars: ?-phrase(('#<'([a,b,c]),'#+'(t(99)),'#*'(p(88)),'#-'(t(A)),'#-'(p(B)),'#:'(X),'#>'(As)),Xs,Ys). -- assumptions.pl",
    "to_boolean(S,B): converts their string representation to booleans true, false -- xrefl.pl",
    "to_dot(Cat,FileName,VerboseVs,VerboseEs): writes out a Cat to a dot file for graphviz visualization -- graphs.pl",
    "to_engine0(Engine,Term) : sends Term to Engine -- builtins.pl",
    "to_file(F,T): saves (large term T, possibly containing serilizable Java objects) to file F -- xbuiltins.pl",
    "to_gui_printer(Name,term): prints to a gui window if it exists -- gui.pl",
    "to_linear(T,CT): converts a term to parser independent representation - ## libs -- cserver.pl",
    "to_rstring(T,S): converts a term T to a symbol such that it can be read back -- xbuiltins.pl",
    "to_set(Xs,Set): converts List of ground elements to set with no duplications -- xbuiltins.pl",
    "to_string(N,S): turns number N to string S -- shared.pl",
    "to_upper_case(S,T), to_lower_case(S,T): convert atoms to upper/lower case -- xbuiltins.pl",
    "token_of(File,T): backtracks over all tokens in File -- xio.pl",
    "token_of(File,T): backtracks over all tokens in given string -- xio.pl",
    "topcall(Goal) : calls Goal trying to use clauses from default database -- db.pl",
    "traceln(Term): writes out term to console directly -- lib.pl",
    "true if X occurs on list Xs - also works as a generator -- lists.pl",
    "true if X occurs on list Xs - only checks -- lists.pl",
    "unify_with_occurs_check(X,Y): true if X Y unifies subject to occurs check - this algorithm always terminates -- lib.pl",
    "unprotect_engine(S): makes sure engine S can be garbage collected -- xbuiltins.pl",
    "unvisit(Agent,Host,Port): agent stops broadcasting its database update to Port -- lagent.pl",
    "use_gui_printer(Name): redirectes output to a GUI window -- gui.pl",
    "used_memory(M): returns amount of memory in Mbytes used so far by this Java VM -- xbuiltins.pl",
    "user_home(Dir): returns user's home directory -- xio.pl",
    "varnumbers(Term,NewTerm): inverse of numbervars - turns VAR terms into vars while keeping other vars unchanged -- xbuiltins.pl",
    "vars_of(Term,Vars) :: extracts set of free varibles Vars occurring in Term -- bagof.pl",
    "visit(Agent,Host,Port): agent broadcasts its database and future updates to Port -- lagent.pl",
    "visiting(Agent,Host,Port): iterates over Host,Port where the agent broadcasts its updates -- lagent.pl",
    "visitor(Agent): true if Agent has visited this space -- lagent.pl",
    "waits until Agent visits - if var(Agent) waits until any agent visits -- lagent.pl",
    "wcompile(File): compiles File.pl to File.wam - can be loaded directly with qcompile(File) - no dynamics -- lfix.pl",
    "wcompile_mt(Files,OutFile): compiles Files concurrently and merges the results to OutFile - a .wam file -- lfix.pl",
    "while(C,G): answers G as far as constraint C holds -- compat.pl",
    "word_of(File,W): backtracks over words found in in a file, one at time -- xio.pl",
    "words2nat(Ws,Ns): interperses words with spaces while making punctuation look natural -- xio.pl",
    "words2sentence(Ws,Sentence): combines words with spaces as needed for a better looking natural language sentence -- xio.pl",
    "words_code(Ws,C): backtracks over all char codes in a list of words -- xio.pl",
    "words_of(File,Words): converts a File to a list of words -- xio.pl",
    "working_directory(Old,New): binds Old to current directory and changes it to New -- xio.pl",
    "write(Stream,Term): writes term to stream -- xio.pl",
    "write_canonical(Stream,Term): writes a term to a stream such that it can be read back -- xio.pl",
    "write_canonical(Term): writes tu current output a term such that it can be read back -- xio.pl",
    "write_codes(Cs): write each char represented by codes in Cs to stream -- xio.pl",
    "writeq(T): writes out T while quoting objects in int when needed -- xio.pl",
    "xappend(File,Db): adds to Db clauses in compressed file -- db.pl",
    "xappend(File,Db): adds to default Db clauses in compressed file -- db.pl",
    "xclause_of(File,Clause): backtracks/iterates over clauses in compressed file -- db.pl",
    "xdb_load(File): replaces all your databases in memory with the content, indexes included -- db.pl",
    "xdb_save(File): saves all your databases to one compressed file, indexes included -- db.pl",
    "xload(File): replaces clauses in default Db with clauses in compressed file -- db.pl",
    "xload(File,Db): replaces all clauses in Db with clauses in compressed file - make sure indexing is on if needed! -- db.pl",
    "xsave(File): saves clause in default Db to compressed file -- db.pl",
    "xsave(File,Db): saves clause in database Db to one compressed file -- db.pl",
    "zipWith(F,Xs,Ys,Zs): for X in Xs and Y in Zs computes and collects Z in Zs such that F(X,Y,Z) -- lists.pl",

    "make_help: generates help file -- help.pl"};
}
